// The v5 scoring dictionary for the GPU → cuda/v5dict.h (the "v5-lite" sieve: splitting the tail and the start into words right on the GPU).
// We take exactly the same dictionary and weights as score_v5.mjs: the word, its length, the base gain 5·len − (9−zipf)·log2(10),
// the function-word multiplier, the theme/slang/personal-rating bonus, the "long" and "content" flags.
//   node src/gpu_dict_v5.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
// the internals of score_v5 are not exported — we load a copy of the module that exports what we need
const src = fs.readFileSync(path.join(here, 'score_v5.mjs'), 'utf8').replace(/^﻿/, '');
const tmp = path.join(here, '.score_v5_dict.tmp.mjs');
fs.writeFileSync(tmp, src + '\nexport { Z, THEME, VOTES, FUNC2 };\n');
const { Z, THEME, VOTES, FUNC2, P5, SLANG_SET } = await import(pathToFileURL(tmp).href).then(async (m) => ({ ...m, SLANG_SET: (await import('./gems.mjs')).SLANG_SET }));
fs.unlinkSync(tmp);

const MAXL = 16;
const rows = [];
for (const [w, z] of Z) {
  if (!/^[a-z0-9]+$/.test(w) || w.length >= MAXL) continue;
  const alpha = /^[a-z]+$/.test(w);
  const content = w.length >= 3 || THEME.has(w);
  const funcMul = !content || (FUNC2.has(w) && w.length <= 3);
  let bonus = THEME.has(w) ? P5.themeBonus : SLANG_SET.has(w) ? P5.strongBonus : 0;
  const v = VOTES.get(w); if (v > 0) bonus += P5.wordLike; else if (v < 0) bonus -= P5.wordDislike;
  const base = P5.bitsPerChar * w.length - (9 - z) * Math.log2(10);
  const long = w.length >= P5.minContent || SLANG_SET.has(w);
  const contentF = (content && !FUNC2.has(w)) || SLANG_SET.has(w);
  const slang = SLANG_SET.has(w);
  rows.push({ w, base, bonus, flags: (alpha ? 1 : 0) | (funcMul ? 2 : 0) | (long ? 4 : 0) | (contentF ? 8 : 0) | (slang ? 16 : 0) });
}
rows.sort((a, b) => (a.w < b.w ? -1 : 1));
const f = (x) => { const v = Math.round(x * 1e4) / 1e4; const t = v.toString(); return (/[.e]/.test(t) ? t : t + '.0') + 'f'; };
let h = `// auto-generated by src/gpu_dict_v5.mjs from score_v5.mjs: ${rows.length} words (the same dictionary and weights as the v5 score)\n`;
h += `#define V5N ${rows.length}\n#define V5MAXL ${MAXL}\n`;
h += `__device__ char V5W[V5N][V5MAXL] = {${rows.map((r) => JSON.stringify(r.w)).join(',')}};\n`;
h += `__device__ unsigned char V5LEN[V5N] = {${rows.map((r) => r.w.length).join(',')}};\n`;
h += `__device__ float V5BASE[V5N] = {${rows.map((r) => f(r.base)).join(',')}};\n`;
h += `__device__ float V5BONUS[V5N] = {${rows.map((r) => f(r.bonus)).join(',')}};\n`;
h += `__device__ unsigned char V5FLAGS[V5N] = {${rows.map((r) => r.flags).join(',')}};   // 1 alphabetic, 2 ×funcK, 4 long, 8 content, 16 slang\n`;
// the P5 weights the kernel needs
const keys = ['bitsPerChar', 'stretchGain', 'stretchCap', 'leetCost', 'funcK', 'vis', 'visDigit', 'visCase', 'visCamel', 'visMixed', 'sepDouble', 'sepCase',
  'digitToFor', 'digitSep', 'startAD', 'startTheme', 'start3', 'start3Vis', 'startK', 'singleK', 'face'];
for (const k of keys) h += `#define P5_${k} ${f(P5[k])}\n`;
const out = path.join(here, '..', 'cuda', 'v5dict.h');
if (fs.existsSync(out) && fs.readFileSync(out, 'utf8') === h) console.log(`v5-lite sieve dictionary: ${rows.length} words, unchanged`);
else { fs.writeFileSync(out, h); console.log(`cuda/v5dict.h: ${rows.length} words, ${(h.length / 1024).toFixed(0)} KB — updated`); }
